# Created with podman-4.1.1
apiVersion: v1
kind: Pod
metadata:
  name: konductor
  labels:
    app: konductor
  annotations:
    io.kubernetes.cri-o.TTY/konductor: "false"
    io.podman.annotations.autoremove/konductor: "TRUE"
    io.podman.annotations.init/konductor: "FALSE"
    io.podman.annotations.label/konductor: disable
    io.podman.annotations.privileged/konductor: "FALSE"
    io.podman.annotations.publish-all/konductor: "FALSE"
    org.opencontainers.image.base.name/konductor: ""
spec:
  containers:
  - name: konductor
    image: ghcr.io/containercraft/konductor:latest
    args:
    - /usr/bin/env
    - connect
    env:
    - name: HOSTNAME
      value: konductor
    ports:
    - containerPort: 2222
      hostPort: 2222
    - containerPort: 7681
      hostPort: 7681
    - containerPort: 8080
      hostPort: 8088
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
      seLinuxOptions:
        type: spc_t
